package handler

type Job struct {
	Category     string   `json:"category"`
	Tags         string   `json:"tags"`
	City         string   `json:"city"`
	Title        string   `json:"title"`
	Salary       string   `json:"salary"`
	Company      string   `json:"company"`
	Recruit      string   `json:"recruit"`
	Requirements []string `json:"requirements"`
	Apply        string   `json:"apply"`
	Deadline     string   `json:"deadline"`
	URL          string   `json:"url"`
	ExtraTag     string   `json:"extraTag"`
}

func builtinJobs() []Job {
	return []Job{
		{
			Category: "design",
			Tags: "应届友好",
			City: "上海",
			Title: "平面设计师",
			Salary: "7K-9K",
			Company: "上海形格艺术设计有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"平面设计或相关专业本科学历", "精通 AI、PS、InDesign 等平面设计软件", "具备品牌VIS设计、平面设计实践经验", "掌握印刷工艺和材质知识", "能将创意概念转化为完整视觉方案", "良好沟通能力和团队协作意识"},
			Apply: "站酷平台在线投递，投递后获取HR邮箱",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTE3Mg==.html",
			ExtraTag: "经验不限",
		},
		{
			Category: "design",
			Tags: "高薪",
			City: "成都",
			Title: "创意视觉设计师（AIGC方向）",
			Salary: "8K-15K",
			Company: "成都市恩叁零科技有限公司 | 成都",
			Recruit: "社招",
			Requirements: []string{"精通 Midjourney、Flux、即梦等主流 AIGC 工具", "掌握PS、AI、Figma等设计软件", "3-5年经验，本科学历", "具备动态设计经验和互联网公司背景优先", "有作品集者优先考虑"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTE3Ng==.html",
			ExtraTag: "AI+设计",
		},
		{
			Category: "design",
			Tags: "高薪",
			City: "上海",
			Title: "AI数字内容创作主管",
			Salary: "20K-30K",
			Company: "W的创造者们（上海纳恩文化艺术） | 上海",
			Recruit: "社招",
			Requirements: []string{"精通Midjourney、Runway、ComfyUI等AI工具，具备本地部署能力", "掌握影视后期（Pr/AE）和动画制作软件", "独立完成分镜脚本及视频制作全流程", "本科及以上，影视编导/数字艺术相关专业", "有短剧项目经验、美术或编导复合背景加分"},
			Apply: "站酷平台在线投递，投递后获取联系方式",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNDk4MA==.html",
			ExtraTag: "高薪",
		},
		{
			Category: "design",
			Tags: "应届友好",
			City: "上海",
			Title: "AI设计师",
			Salary: "10K-15K",
			Company: "W的创造者们（上海纳恩文化艺术） | 上海",
			Recruit: "社招",
			Requirements: []string{"熟练使用Stable Diffusion、Midjourney、ComfyUI等AIGC工具", "掌握Photoshop、Illustrator等平面软件", "熟练掌握PR/AE/剪映等非线性编辑工具", "本科及以上学历，相关专业优先", "需提供AIGC作品集"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNDk4NA==.html",
			ExtraTag: "经验不限",
		},
		{
			Category: "design",
			Tags: "",
			City: "上海",
			Title: "品牌设计师",
			Salary: "7K-12K",
			Company: "上海博尚包装设计有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"本科及以上，设计专业背景优先", "1年以上品牌/平面/包装设计经验", "掌握AI软件工具及Mac OS系统", "具备独立完成全案项目的能力", "五险一金，稳定踏实的工作风格"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTAyMA==.html",
			ExtraTag: "",
		},
		{
			Category: "design",
			Tags: "应届友好",
			City: "上海",
			Title: "博物文创设计师",
			Salary: "8K-9K",
			Company: "上海贤莅信息科技有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"美术功底扎实，审美能力优秀", "熟练使用相关设计软件", "具备独立完成设计任务的能力", "学习能力强，有创新意识", "沟通清晰，良好团队协作精神", "经验和学历不限，热爱传统文化者优先"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTA0NA==.html",
			ExtraTag: "经验不限",
		},
		{
			Category: "design",
			Tags: "高薪",
			City: "北京",
			Title: "艺术家具设计师",
			Salary: "10K-20K",
			Company: "癸罡（北京）文化艺术有限公司 | 北京",
			Recruit: "社招",
			Requirements: []string{"产品设计、工业设计等相关专业本科及以上", "3年以上家具/家居产品完整开发经验", "精通Rhino、3D MAX、ZBrush、Keyshot等软件", "熟悉家具材料与生产工艺", "理解人体工学与结构原理"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTA1Mg==.html",
			ExtraTag: "",
		},
		{
			Category: "design",
			Tags: "高薪",
			City: "北京",
			Title: "创意设计师",
			Salary: "17K-30K",
			Company: "癸罡（北京）文化艺术有限公司 | 北京",
			Recruit: "社招",
			Requirements: []string{"本科及以上，艺术设计/视觉传达相关专业", "3-5年广告/文化艺术公司工作经验", "精通Photoshop、Illustrator等专业软件", "审美出众、创意能力强", "良好的沟通表达与团队合作意识"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTA2MA==.html",
			ExtraTag: "高薪",
		},
		{
			Category: "design",
			Tags: "高薪",
			City: "北京",
			Title: "三维设计师",
			Salary: "15K-25K",
			Company: "北京复合创意文化传播有限公司 | 北京",
			Recruit: "社招",
			Requirements: []string{"熟练使用Cinema 4D进行三维渲染", "美术功底深厚，具备手绘/动画能力优先", "细致认真、富有创新精神", "经验和学历不限"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNDk2OA==.html",
			ExtraTag: "",
		},
		{
			Category: "design",
			Tags: "",
			City: "深圳",
			Title: "UI设计师（3C类）",
			Salary: "7K-11K",
			Company: "深圳市达利设计有限公司 | 深圳",
			Recruit: "社招",
			Requirements: []string{"设计相关专业，对UI及视觉有深刻理解", "掌握Photoshop、Illustrator、Sketch、AE", "理解PC端和移动端设计规范", "具备产品思维和交互能力", "专科及以上学历"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTA0MA==.html",
			ExtraTag: "",
		},
		{
			Category: "design",
			Tags: "应届友好",
			City: "其他",
			Title: "Blender 3D设计师",
			Salary: "按项目结算",
			Company: "东莞摩尔微视科技有限公司 | 东莞",
			Recruit: "社招",
			Requirements: []string{"熟悉Blender软件，能开发3D模型", "构建三维立体动态效果（用于全息3D光刻）", "经验和学历不限，兼职起步可转全职"},
			Apply: "站酷平台在线投递（www.more-vision.com）",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTE1Mg==.html",
			ExtraTag: "经验不限",
		},
		{
			Category: "design",
			Tags: "高薪",
			City: "北京",
			Title: "潮玩主设计（二次元/文创）",
			Salary: "25K-40K",
			Company: "大连艾汉特咨询服务有限公司 | 北京",
			Recruit: "社招",
			Requirements: []string{"3-4年二次元概念设计经验", "精通二次元风格，擅长角色和场景概念设计", "具备插画绘制能力", "熟练使用PS、SAI等设计软件", "热爱二次元文化，本科学历"},
			Apply: "站酷平台在线投递（本周最新发布）",
			Deadline: "2026年4月最新",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTMyOA==.html",
			ExtraTag: "高薪",
		},
		{
			Category: "design",
			Tags: "应届友好",
			City: "广州",
			Title: "餐饮品牌设计师（双休）",
			Salary: "6K-10K",
			Company: "广州知尖品牌顾问有限公司 | 广州",
			Recruit: "社招",
			Requirements: []string{"美术、平面设计相关专业，大专以上", "对标志、VI、画册设计有全面把握", "创意企划能力强，沟通表达能力强", "熟悉Midjourney等AI绘画工具优先", "良好审美素养，热爱设计"},
			Apply: "站酷平台在线投递（4月最新发布）",
			Deadline: "2026年4月最新",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTM0OA==.html",
			ExtraTag: "双休",
		},
		{
			Category: "design",
			Tags: "",
			City: "广州",
			Title: "UI设计师（海外App方向/双休）",
			Salary: "7K-10K",
			Company: "广州积贝科技有限公司 | 广州",
			Recruit: "社招",
			Requirements: []string{"1-3年海外App UI设计经验", "美术/设计相关专业", "熟练使用AE、Figma、蓝湖等工具", "对色彩排版视觉细节把控力强", "需附近期作品集（含主导项目）", "AI设计工具经验、英语四六级优先"},
			Apply: "站酷平台在线投递（4月最新发布）",
			Deadline: "2026年4月最新",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTMzMg==.html",
			ExtraTag: "",
		},
		{
			Category: "design",
			Tags: "校招,应届友好",
			City: "杭州",
			Title: "游戏平面设计实习生",
			Salary: "2K-3K",
			Company: "杭州玉尊信息科技有限公司 | 杭州",
			Recruit: "校招",
			Requirements: []string{"大专及以上在读/应届学生", "视觉传达、艺术设计、数字媒体等专业优先", "熟练使用Photoshop、Illustrator", "良好审美与版式能力", "对游戏美术风格有理解和兴趣", "能保证稳定实习时长，有作品优先"},
			Apply: "站酷平台在线投递（4月最新发布）",
			Deadline: "2026年4月最新",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTM0MA==.html",
			ExtraTag: "实习/应届",
		},
		{
			Category: "design",
			Tags: "校招,大厂,应届友好",
			City: "北京",
			Title: "字节跳动 - 设计类校招岗",
			Salary: "高薪（大厂待遇）",
			Company: "字节跳动 | 北京/上海/深圳/杭州/成都等",
			Recruit: "校招",
			Requirements: []string{"2025.9-2026.8毕业的全日制应届生", "设计类方向含交互设计、视觉设计、用户研究等", "5000+Offer，8大职类全年开放投递", "需具备AI+专业的复合能力（AIGC辅助创意）", "越早投递Offer几率越高"},
			Apply: "字节跳动校招官网在线投递，每人2次投递机会",
			Deadline: "全年开放",
			URL: "https://jobs.bytedance.com/campus",
			ExtraTag: "2026校招",
		},
		{
			Category: "design",
			Tags: "应届友好",
			City: "其他",
			Title: "平面设计师",
			Salary: "5K-9K",
			Company: "安徽源创环境艺术工程有限公司 | 六安",
			Recruit: "社招",
			Requirements: []string{"本科学历，视觉设计/传达等专业优先", "熟练运用AI/PS软件", "良好审美能力，对美感有较高敏锐度"},
			Apply: "六安市人社局官网查看联系方式",
			Deadline: "2026年4月",
			URL: "https://rsj.luan.gov.cn/public/6608261/10757591.html",
			ExtraTag: "应届可投",
		},
		{
			Category: "design",
			Tags: "高薪",
			City: "杭州",
			Title: "AI平面设计师",
			Salary: "12K-16K",
			Company: "杭州兴耀商业经营管理有限公司 | 杭州",
			Recruit: "社招",
			Requirements: []string{"丰富平面设计经验，有一定视觉审美", "真正在用AI做设计，有自己的工作流", "对AI赋能商业内容有想法", "3-5年经验，本科学历", "专注商业空间、内容营销、小红书投流方向"},
			Apply: "站酷平台在线投递（4月最新发布）",
			Deadline: "2026年4月最新",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTM0NA==.html",
			ExtraTag: "AI+设计",
		},
		{
			Category: "edit",
			Tags: "应届友好",
			City: "武汉",
			Title: "短视频剪辑师",
			Salary: "6K-12K",
			Company: "BOSS直聘热招 | 武汉",
			Recruit: "社招",
			Requirements: []string{"大专及以上学历", "熟练使用PR、AE、剪映等剪辑工具", "经验不限，有短视频作品优先", "有一定的镜头语言理解能力和画面节奏感"},
			Apply: "BOSS直聘APP在线沟通投递",
			Deadline: "持续招聘",
			URL: "https://www.zhipin.com/zhaopin/b2b6079e3f2de5eb1XBz3dk~/",
			ExtraTag: "应届可投",
		},
		{
			Category: "edit",
			Tags: "高薪",
			City: "北京",
			Title: "视频后期剪辑师",
			Salary: "8K-15K",
			Company: "BOSS直聘精选 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"熟练使用Premiere、After Effects、DaVinci Resolve", "具备调色、特效制作能力", "有短视频或商业广告剪辑经验优先", "良好的审美和画面节奏感"},
			Apply: "BOSS直聘APP在线沟通投递",
			Deadline: "持续招聘",
			URL: "https://www.zhipin.com/zhaopin/ed1f13ea403820d303J43Nq0/",
			ExtraTag: "经验不限",
		},
		{
			Category: "edit",
			Tags: "高薪",
			City: "上海",
			Title: "AI视频美术/AI指导",
			Salary: "15K-25K",
			Company: "上海聚龙广告有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"1年以上广告/影视/设计相关经验", "美术功底扎实，优秀视觉审美", "熟练运用主流AIGC工具", "对AI技术在广告创作中的应用感兴趣", "本科学历，沟通协作能力强"},
			Apply: "站酷平台在线投递（4月最新发布）",
			Deadline: "2026年4月最新",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTM3Ng==.html",
			ExtraTag: "高薪",
		},
		{
			Category: "edit",
			Tags: "应届友好",
			City: "上海",
			Title: "AI视频制作",
			Salary: "8K-12K",
			Company: "上海意类广告有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"0-3年工作经验，学历不限", "对短视频创作有热爱和审美品味", "需提供个人AIGC作品", "有导演经验优先"},
			Apply: "站酷平台在线投递（4月最新发布）",
			Deadline: "2026年4月最新",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTM3Mg==.html",
			ExtraTag: "经验不限",
		},
		{
			Category: "edit",
			Tags: "应届友好",
			City: "武汉",
			Title: "短剧剪辑师",
			Salary: "6K-10K",
			Company: "BOSS直聘 | 武汉·洪山区",
			Recruit: "社招",
			Requirements: []string{"熟练使用PR/AE等后期工具", "较强的故事叙事能力和节奏把控", "了解短剧市场趋势", "有作品者优先"},
			Apply: "BOSS直聘APP在线沟通投递",
			Deadline: "持续招聘",
			URL: "https://www.zhipin.com/zhaopin/143ba8430816e5f003V92NW6FQ~~/",
			ExtraTag: "",
		},
		{
			Category: "edit",
			Tags: "校招,大厂,应届友好",
			City: "北京",
			Title: "字节跳动 - 运营类校招岗（含内容/视频方向）",
			Salary: "高薪（大厂待遇）",
			Company: "字节跳动 | 北京/上海/深圳/成都等",
			Recruit: "校招",
			Requirements: []string{"2025.9-2026.8毕业的应届生", "运营类含内容运营/视频审核/项目管理等方向", "需具备AI工具应用能力（视频制作/图像编辑）", "每人2次投递机会，全年开放"},
			Apply: "字节跳动校招官网在线投递",
			Deadline: "全年开放",
			URL: "https://jobs.bytedance.com/campus",
			ExtraTag: "2026校招",
		},
		{
			Category: "operate",
			Tags: "应届友好",
			City: "北京",
			Title: "新媒体运营专员",
			Salary: "5K-8K",
			Company: "BOSS直聘热招 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"负责微信/视频号/抖音等平台的日常运营", "热点追踪、选题策划、文案撰写", "视觉设计与视频创意、数据分析", "零经验可投，提供岗前培训"},
			Apply: "BOSS直聘APP在线沟通投递",
			Deadline: "持续招聘",
			URL: "https://www.zhipin.com/zhaopin/c3e1696eaca1c39a1nVz3NS7/",
			ExtraTag: "应届友好",
		},
		{
			Category: "operate",
			Tags: "应届友好",
			City: "上海",
			Title: "数智营销专员",
			Salary: "面议",
			Company: "上海幻晶纳科新材料有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"本科以上，市场营销等相关专业", "负责社交媒体运营、内容策划、互动运营", "探索AI工具在营销中的应用", "掌握网络沟通能力，有创新意识", "提供完善福利和培训体系"},
			Apply: "发送简历至 selinawhimsy@163.com",
			Deadline: "2026年有效",
			URL: "https://www.shanghai.gov.cn/nw17239/20260116/7d878b8fcb67438b92e4ccfb5f70e938.html",
			ExtraTag: "应届可投",
		},
		{
			Category: "operate",
			Tags: "应届友好",
			City: "上海",
			Title: "市场策划（新媒体方向）",
			Salary: "面议",
			Company: "上海幻晶纳科新材料有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"本科以上学历", "负责宣传文案撰写和物料美术设计", "新媒体平台运营维护", "掌握PS、AI等设计软件", "优秀文字创作能力"},
			Apply: "发送简历至 selinawhimsy@163.com",
			Deadline: "2026年有效",
			URL: "https://www.shanghai.gov.cn/nw17239/20260116/7d878b8fcb67438b92e4ccfb5f70e938.html",
			ExtraTag: "",
		},
		{
			Category: "operate",
			Tags: "高薪",
			City: "北京",
			Title: "新媒体运营（猎聘精选）",
			Salary: "8K-15K",
			Company: "猎聘平台精选 | 北京",
			Recruit: "社招",
			Requirements: []string{"熟悉小红书/抖音/微信等平台算法机制", "负责内容运营与粉丝增长策略", "有运营过达人账号或企业号经验优先", "数据分析能力，能产出运营复盘报告"},
			Apply: "猎聘平台在线投递",
			Deadline: "持续招聘",
			URL: "https://www.liepin.com/job/1976638119.shtml",
			ExtraTag: "高薪",
		},
		{
			Category: "operate",
			Tags: "应届友好",
			City: "北京",
			Title: "新媒体运营（前程无忧精选）",
			Salary: "6K-10K",
			Company: "前程无忧平台 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"公众号运营/短视频运营/社群运营等方向", "多家企业在招，支持按城市和薪资筛选", "部分岗位接受应届零经验", "具备内容创作与数据分析能力"},
			Apply: "前程无忧平台在线投递",
			Deadline: "持续更新",
			URL: "https://jobs.51job.com/xinmeitiyunying/",
			ExtraTag: "应届友好",
		},
		{
			Category: "operate",
			Tags: "校招,应届友好",
			City: "广州",
			Title: "品宣综合岗（央国企·2026校招）",
			Salary: "面议（央国企）",
			Company: "广州新锐光掩模科技有限公司 | 广州",
			Recruit: "校招",
			Requirements: []string{"本科及以上学历", "公共关系、新闻传播、中文等专业", "负责企业品牌宣传与新媒体运营", "央国企待遇"},
			Apply: "详见知乎岗位合集中的投递链接",
			Deadline: "招满即止",
			URL: "https://zhuanlan.zhihu.com/p/1999913181557065476",
			ExtraTag: "央国企",
		},
		{
			Category: "photo",
			Tags: "应届友好",
			City: "其他",
			Title: "商业摄影师/新媒体摄影",
			Salary: "5K-8K",
			Company: "安徽斛生记生物科技有限公司 | 六安",
			Recruit: "社招",
			Requirements: []string{"精通各类商业摄影技巧", "出色的审美能力和创意思维", "拍摄产品图、场景图和人物图", "良好团队合作精神，强烈责任心"},
			Apply: "六安市人社局官网查看联系方式",
			Deadline: "2026年4月",
			URL: "https://rsj.luan.gov.cn/public/6608261/10757591.html",
			ExtraTag: "应届可投",
		},
		{
			Category: "photo",
			Tags: "高薪",
			City: "武汉",
			Title: "编导拍摄剪辑",
			Salary: "8K-15K",
			Company: "BOSS直聘热招 | 武汉·江汉区",
			Recruit: "社招",
			Requirements: []string{"短视频内容策划、拍摄与剪辑全流程", "有镜头语言理解能力", "熟练使用拍摄设备和后期软件", "有创意策划能力和团队协作意识"},
			Apply: "BOSS直聘APP在线沟通投递",
			Deadline: "持续招聘",
			URL: "https://www.zhipin.com/zhaopin/143ba8430816e5f003V92NW6FQ~~/",
			ExtraTag: "高薪",
		},
		{
			Category: "photo",
			Tags: "央媒/国企,校招,应届友好",
			City: "北京",
			Title: "品牌管培生（拍摄/视觉方向）",
			Salary: "面议（央企待遇）",
			Company: "阳光保险集团 | 全国",
			Recruit: "校招",
			Requirements: []string{"2026年应届毕业生", "影视制作、数字媒体艺术等相关专业", "负责短视频拍摄、后期剪辑和视觉优化", "央企福利：五险一金，系统培养体系"},
			Apply: "阳光保险校招官网在线申请",
			Deadline: "校招进行中",
			URL: "https://sunzhaopin.sinosig.com/campusxq?c=&d=3&jc=2&jobId=621023335&jobcatefullName=%E9%9B%86%E5%9B%A2&p=1%2C3%5E-1",
			ExtraTag: "2026管培生",
		},
		{
			Category: "photo",
			Tags: "",
			City: "武汉",
			Title: "拍摄剪辑短视频",
			Salary: "8K-12K",
			Company: "BOSS直聘 | 武汉·武昌区",
			Recruit: "社招",
			Requirements: []string{"具备独立拍摄能力", "熟悉灯光布景、基础调色", "掌握特效制作基础", "有作品集者优先"},
			Apply: "BOSS直聘APP在线沟通投递",
			Deadline: "持续招聘",
			URL: "https://www.zhipin.com/zhaopin/6b4e628f1ecf29370nR_2t20Ew~~/",
			ExtraTag: "",
		},
		{
			Category: "photo",
			Tags: "应届友好",
			City: "北京",
			Title: "摄影摄像实习生",
			Salary: "5K-10K",
			Company: "BOSS直聘 | 北京",
			Recruit: "校招",
			Requirements: []string{"在校生/应届生，本科学历", "影视、摄影相关专业", "提供带薪培训", "有个人摄影作品集优先"},
			Apply: "BOSS直聘APP在线沟通投递",
			Deadline: "持续招聘",
			URL: "https://www.zhipin.com/zhaopin/ad0a829f11cce3310nx82NS0/",
			ExtraTag: "应届可投",
		},
		{
			Category: "photo",
			Tags: "应届友好",
			City: "北京",
			Title: "摄影/摄像岗位（应届生合集）",
			Salary: "5K-13K",
			Company: "应届生求职网精选 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"应届生摄影招聘专区，全国各地岗位汇总", "商业摄影、产品摄影、视频拍摄等方向", "各岗位要求不同，多数无需丰富经验", "支持按城市和方向筛选"},
			Apply: "应届生求职网在线投递",
			Deadline: "持续更新",
			URL: "https://zhiwei.yingjiesheng.com/sheying/",
			ExtraTag: "应届专区",
		},
		{
			Category: "news",
			Tags: "央媒/国企",
			City: "北京",
			Title: "全媒体记者/编辑（人民日报社）",
			Salary: "事业编制",
			Company: "人民日报社 | 北京",
			Recruit: "社招",
			Requirements: []string{"硕士研究生及以上学历", "新闻、传播等相关专业", "政治立场坚定，良好的文字功底", "拟聘8人，事业编制", "多个岗位方向，共招聘32人"},
			Apply: "人民日报社公开招聘系统在线报名",
			Deadline: "关注官网公告",
			URL: "http://hr.peopledaily.com.cn/Recruitment/x/job/list.html",
			ExtraTag: "央媒",
		},
		{
			Category: "news",
			Tags: "央媒/国企,应届友好",
			City: "北京",
			Title: "记者/编辑（新华社）",
			Salary: "事业编制",
			Company: "新华社 | 全国",
			Recruit: "社招",
			Requirements: []string{"新闻传播、文学、法学、经济学等专业", "记者岗：外出采访写稿", "编辑岗：办公室稿件修改审核", "共招聘205人（总社134名+分社71名）", "事业编制，全国多个驻地"},
			Apply: "新华社招聘官网报名，邮箱 xinhuashezhaopin@xinhua.org",
			Deadline: "关注官网公告",
			URL: "http://www.news.cn/xhs/hr/index.htm",
			ExtraTag: "央媒",
		},
		{
			Category: "news",
			Tags: "央媒/国企",
			City: "北京",
			Title: "央视网校招岗位",
			Salary: "面议（央媒）",
			Company: "央视网 | 北京及全国",
			Recruit: "校招",
			Requirements: []string{"涵盖编辑、记者、新媒体运营等多种岗位", "工作地点覆盖全国多个城市", "新闻传播等相关专业优先", "具体要求详见各岗位说明"},
			Apply: "央视网招聘官网在线报名",
			Deadline: "关注官网",
			URL: "https://career.cntv.cn/",
			ExtraTag: "央媒",
		},
		{
			Category: "news",
			Tags: "央媒/国企,校招,应届友好",
			City: "广州",
			Title: "编辑/记者（南方出版传媒·2026校招）",
			Salary: "面议",
			Company: "南方出版传媒 | 广州",
			Recruit: "校招",
			Requirements: []string{"六大类岗位，51个具体职位，招聘86人", "包含编辑类和记者类岗位", "面向新闻传播学、中文等专业应届毕业生", "国有出版传媒集团，福利完善"},
			Apply: "前程无忧南方出版传媒校招专页在线投递",
			Deadline: "校招进行中",
			URL: "http://campus.51job.com/nfcb2026/",
			ExtraTag: "2026校招",
		},
		{
			Category: "news",
			Tags: "应届友好",
			City: "北京",
			Title: "记者/编辑岗位（应届生合集）",
			Salary: "多档薪资",
			Company: "应届生求职网 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"全国各地记者/编辑岗位汇总", "报社、杂志、网站、新媒体等方向", "大多数岗位无需丰富工作经验", "支持按城市和行业筛选"},
			Apply: "应届生求职网在线投递",
			Deadline: "持续更新",
			URL: "https://zhiwei.yingjiesheng.com/jizhe/",
			ExtraTag: "应届专区",
		},
		{
			Category: "news",
			Tags: "应届友好",
			City: "北京",
			Title: "传媒类岗位（应届生合集）",
			Salary: "多档薪资",
			Company: "应届生求职网 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"传媒行业招聘合集", "内容编辑、栏目策划、新闻采编、融媒体运营等", "多家传媒机构在招应届毕业生", "支持按方向筛选"},
			Apply: "应届生求职网在线投递",
			Deadline: "持续更新",
			URL: "https://zhiwei.yingjiesheng.com/chuanmei/",
			ExtraTag: "应届专区",
		},
		{
			Category: "space",
			Tags: "应届友好",
			City: "上海",
			Title: "空间设计师",
			Salary: "6K-7K",
			Company: "上海形格艺术设计有限公司 | 上海",
			Recruit: "社招",
			Requirements: []string{"建筑学/室内设计/产品设计相关专业，本科以上", "3-5年相关经验", "具备设计深化与施工深化能力", "熟练掌握CAD、SU、PS等设计软件", "有商业空间从创意到实施的实战经验"},
			Apply: "发送简历至 Hr@sigedesign.com",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNTE2OA==.html",
			ExtraTag: "",
		},
		{
			Category: "space",
			Tags: "校招,应届友好",
			City: "北京",
			Title: "室内设计师（2026校招）",
			Salary: "6K-11K",
			Company: "杰地设计集团 | 全国多地",
			Recruit: "校招",
			Requirements: []string{"环境设计/室内设计等相关专业应届毕业生", "设计师、摄影师、实习生等多岗位可选", "具备空间设计基本功和软件能力", "系统化培训和成长路径"},
			Apply: "鼠鼠求职平台在线投递",
			Deadline: "校招进行中",
			URL: "https://www.shushuqiuzhi.com/article/150812",
			ExtraTag: "2026校招",
		},
		{
			Category: "space",
			Tags: "",
			City: "上海",
			Title: "展示展览空间设计师",
			Salary: "8K-15K",
			Company: "智联招聘精选 | 上海",
			Recruit: "社招",
			Requirements: []string{"展览空间整体设计方案制定和实施", "掌握3Dmax、CAD、PS等设计软件", "有展览馆/博物馆设计经验优先", "空间感知能力和艺术审美"},
			Apply: "智联招聘平台在线投递",
			Deadline: "持续招聘",
			URL: "https://www.zhaopin.com/zhaopin/9c6df1bd7f254300acf04f968650fc3a/",
			ExtraTag: "",
		},
		{
			Category: "space",
			Tags: "校招,大厂,应届友好",
			City: "深圳",
			Title: "TCL校招设计岗",
			Salary: "面议（大厂待遇）",
			Company: "TCL集团 | 全国多地",
			Recruit: "校招",
			Requirements: []string{"2025.9-2026.12毕业的应届毕业生", "产品设计/空间设计/交互设计等方向", "艺术设计相关专业", "大厂平台与成长机会"},
			Apply: "TCL校招官网在线投递",
			Deadline: "校招进行中",
			URL: "https://zhaopin.tcl.com/campus",
			ExtraTag: "2026校招",
		},
		{
			Category: "space",
			Tags: "",
			City: "上海",
			Title: "艺术展览空间设计",
			Salary: "8K-12K",
			Company: "智联招聘精选 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"艺术展览空间的整体设计与布展规划", "环境设计或相关专业", "具备空间感知能力和艺术审美", "熟练使用3D建模和渲染软件"},
			Apply: "智联招聘平台在线投递",
			Deadline: "持续招聘",
			URL: "https://m.zhaopin.com/zhaopin/7d54a21e045d4e829c4e9a3caf96eedd/",
			ExtraTag: "",
		},
		{
			Category: "space",
			Tags: "应届友好",
			City: "北京",
			Title: "室内设计师（应届生合集）",
			Salary: "6K-11K",
			Company: "猎聘平台 | 全国多地",
			Recruit: "社招",
			Requirements: []string{"室内设计师岗位合集，覆盖全国各大城市", "多家设计公司招聘应届毕业生", "提供系统培训和职业成长路径", "支持按城市和薪资筛选"},
			Apply: "猎聘平台在线投递",
			Deadline: "持续更新",
			URL: "https://www.liepin.com/zpshineishejishi/",
			ExtraTag: "应届专区",
		},
		{
			Category: "space",
			Tags: "",
			City: "北京",
			Title: "平面设计师（餐饮空间方向）",
			Salary: "10K-12K",
			Company: "大连唯品建筑装饰设计工程有限公司 | 北京",
			Recruit: "社招",
			Requirements: []string{"本科学历，3-5年工作经验", "熟练使用PS、AI、CDR等设计软件", "具备审美、排版、色彩搭配、构图能力", "理解品牌、营销、用户视觉逻辑", "有餐饮设计经验优先"},
			Apply: "站酷平台在线投递",
			Deadline: "长期有效",
			URL: "https://www.zcool.com.cn/opportunity/post/ZNDk5Ng==.html",
			ExtraTag: "",
		},
	}
}
